### ISSUE TITLE
Refactor GripNet 

### ISSUE THREAD

**Issue by haipinglu** [pykale/pykale#170]
Refactor GripNet like DeepDTA

**Comment by haipinglu** [comment]
GripNet is for graphs, particular KG. Refactor it into a data integration/multimodal learning pipeline?@pz-white

**Comment by pz-white** [comment]
I can refactor it to adapt the heterogeneous biomedical network, which I always wanted to do before. PyG 2.0 is a good chance as there are many heterogeneous features can be used for reference, but I need to finish my current work first. I estimate the refactor can kick as early as mid-October. @haipinglu

**Comment by haipinglu** [comment]
@Lyric-19 is working on it.
