### ISSUE TITLE
Convert notebook tutorials from section to a markdown under getting started

### ISSUE THREAD

**Issue by haipinglu** [pykale/pykale#172]
Convert notebook tutorials from section to a markdown under getting started

**Comment by bobturneruk** [comment]
Also fix broken links in https://github.com/pykale/pykale/blob/main/examples/digits_dann_lightn/tutorial.ipynb

**Comment by bobturneruk** [comment]
May be relevant https://jupyter-sphinx.readthedocs.io/en/latest/
