### ISSUE TITLE
Running Test Files

### ISSUE THREAD

**Issue by kennedy12335** [pykale/pykale#181]
### Discussed in https://github.com/pykale/pykale/discussions/180

<div type='discussions-op-text'>

<sup>Originally posted by **kennedy12335** July 13, 2021</sup>
I am currently trying to run the test_csv_logger.py file and I am encountering an error. It cannot locate files from the folder containing the test data. I believe the test data is downloaded automatically from the confest.py script and I assume that is when the test_data folder would be created. I may be wrong but that was what I understood from https://github.com/pykale/pykale/blob/main/tests/README.md. Can someone please explain why I am getting errors. To be precise this is the error I am getting:

_E           FileNotFoundError: [Errno 2] No such file or directory: 'tests/test_data/parameters.json'

kale/utils/csv_logger.py:66: FileNotFoundError_</div>

**Comment by bobturneruk** [comment]
Why was this closed, please, @haipinglu?
