### ISSUE TITLE
Dependabot

### ISSUE THREAD

**Issue by haipinglu** [pykale/pykale#186]
### Discussed in https://github.com/pykale/pykale/discussions/179

<div type='discussions-op-text'>

<sup>Originally posted by **bobturneruk** July  6, 2021</sup>
dependabot might help us learn of potential problems caused by dependency updates so we can fix them early:

https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates

I'll have a bit more of a look, but I'm interested in others' views.</div>

**Comment by bobturneruk** [comment]
Dependabot is now enabled. I'll leave this issue open for now to remind me to monitor it.
