### ISSUE TITLE
[Docs] Possible help in converting unittests to pytest

### ISSUE THREAD

**Issue by kennedy12335** [pykale/pykale#191]
# 📚 Documentation

https://github.com/pytest-dev/unittest2pytest Is a good tool to help convert unit tests code written in unittest to pytest. It may be beneficial to include this in https://github.com/pykale/pykale/blob/main/tests/README.md as it saves some time rather than re-writing the entire code. It does not provide a 100% conversion but it is a very good way to start.

**Comment by dannysepler** [comment]
Hi! I wrote a similar pip package, if you're still shopping around for how to do this https://github.com/dannysepler/pytestify -- totally cool if unittest2pytest fits your needs more. There are some implementation differences
