### ISSUE TITLE
[Feature Request] Tests for notebooks

### ISSUE THREAD

**Issue by bobturneruk** [pykale/pykale#214]
# 🚀 Feature Request

Add basic tests for the tutorial notebooks. 

## Motivation

Changes to dependencies can cause notebooks to fail unexpectedly.

## Pitch

Using GitHub actions, these should:

- Set up an appropriate execution environment
- Convert the notebook to a script
- Run the script
- Report failure if there is an error

**Describe alternatives you've considered**

Regression tests would be very time consuming.

**Are you willing to open a pull request?** Yes

**Comment by haipinglu** [comment]
@bobturneruk Will this be implemented soon? We got another problem with the recent PR #218, where the bug in the digits notebook is undetected. I only manually discovered today.
https://colab.research.google.com/github/pykale/pykale/blob/main/examples/digits_dann_lightn/tutorial.ipynb

**Comment by bobturneruk** [comment]
Sorry to hear about that. I will make some time for this tomorrow.
