### ISSUE TITLE
[Bug installing Pykale - missing "kale.loaddata.image_access"

### ISSUE THREAD

**Issue by 19valentin99** [pykale/pykale#232]
# 🐛 Bug in installing Pykale

## To reproduce

1. Install PyKale in a new environment
2. Install the PyKale Git Repository
3. Try to run the "python main.py --cfg configs/tutorial_svc.yaml" (typo corrected in previous bug report)
4. Will display an error: kale.loaddata.image_access does not exist
5. Go into the place where the environment is set-up, in my case: C:\Users\vcrac\anaconda3\envs\torch\Lib\site-packages\kale\loaddata and find out that "image_access.py" is missing.

Quick fix of the problem:

1.Create in the "..\Lib\site-packages\kale\loaddata" a file named "image_access.py" and paste the code cade is available on git (https://github.com/pykale/pykale/tree/main/kale/loaddata/image_access/py)
![image_example_image_access](https://user-images.githubusercontent.com/27396461/137022003-d594a17f-1c9f-486c-85aa-23201bc2857e.png)

Long fix:
1. I am not sure how to check/ modify the packages that are on the pip pykale in order for "image_access.py" to be included when using "pip install pykale"

**Comment by haipinglu** [comment]
@19valentin99 We released a new version 0.1.0.rc4. If you do a pip upgrade https://stackoverflow.com/questions/47071256/how-to-update-upgrade-a-package-using-pip, you should have the new API and the error should be gone. If not, please report here what happened and we will resolve it.
