### ISSUE TITLE
[Refactor] Variable name consistency-"val" in variable names to "valid"

### ISSUE THREAD

**Issue by XianyuanLiu** [pykale/pykale#275]
- Shall we unify the validation abbreviation in docs/variables/functions from `val` to `valid` according to [fastai](https://docs.fast.ai/dev/abbr.html)? Some in PyKale use `val` but others use `valid`.

- Modules that will be modified
![image](https://user-images.githubusercontent.com/19544506/145715177-6f024f8c-f1dd-4905-b44a-aa9dcd7e31c4.png)

- Impact on speed - Nope

- Will this be a breaking change? -Nope

**Comment by XianyuanLiu** [comment]
Both are used in our pykale now ([`valid`](https://github.com/pykale/pykale/search?q=valid) and [`val`](https://github.com/pykale/pykale/search?q=val)). There are two abbreviations for training/validation/test: one is trn/val/tst, the other is train/valid/test. The latter may be easier to pronounce and understand.

**Comment by haipinglu** [comment]
Agreed on `valid`

**Comment by XianyuanLiu** [comment]
I have met two problems in changing process.
1. `valid` used in PyKale is not only for `validation`, e.g. [`multi_domain`](https://github.com/pykale/pykale/blob/main/kale/loaddata/multi_domain.py#L316). It means legal and can be accepted. Antonym is `void`.   
2. In PyTorch-lightning, they used `val_` in core, e.g. [`trainer`](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/trainer.py#L1024), but `valid_` somewhere in test, e.g. [`helper`](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/tests/helpers/datamodules.py#L74) and [`logging`](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/tests/trainer/logging_/test_eval_loop_logging.py#L559).

Sorry I haven't noticed these problems before. I have checked some popular libraries for DL and ML.
[fastai](https://github.com/fastai/fastai) and [sklearn](https://github.com/scikit-learn/scikit-learn) uses both but `valid` more. [keras](https://github.com/keras-team/keras) and [open-mmlab](https://github.com/open-mmlab/mmdetection) uses `val`.

May I know your opinions please, which one do you prefer now? @sz144 @pz-white @RaivoKoot

**Comment by RaivoKoot** [comment]
Still prefer `valid`
