### ISSUE TITLE
[Feature Request] A second chance in scheduled tests

### ISSUE THREAD

**Issue by haipinglu** [pykale/pykale#278]
# 🚀 Feature Request

Give a second chance upon a scheduled test fail.

## Motivation

Recent fails in scheduled tests are all due to a temporary server issue at Zenodo that can be fixed by a simple rerun after a few hours. Why not automate this to reduce the overhead and reduce "false alarms"? Hence the suggestion above.

## Pitch

In the scheduled tests, if failed for the first time, wait for a few (e.g. 5) hours to run it again and raise an issue only if the second run after a few hours fails too.

**Comment by bobturneruk** [comment]
Good idea @haipinglu - I'll have a look at this.

**Comment by bobturneruk** [comment]
Note to self: This may be useful https://docs.github.com/en/actions/advanced-guides/storing-workflow-data-as-artifacts#passing-data-between-jobs-in-a-workflow

**Comment by haipinglu** [comment]
@bobturneruk Possible to have this implemented in view of the failure today? Many thanks.

**Comment by bobturneruk** [comment]
I'll do my best to make time for it.

**Comment by bobturneruk** [comment]
Is there a particular test, or tests that are implicated in this, please?

**Comment by haipinglu** [comment]
@bobturneruk As discussed, this could be closed.
