### ISSUE TITLE
About random seed

### ISSUE THREAD

**Issue by XianyuanLiu** [pykale/pykale#30]
https://github.com/pykale/pykale/blob/3c88f85ae09e40325eea2da141893240127a6ab7/kale/utils/seed.py#L10

Do we need to set the seed for GPU to reproduce the result like [MMCV](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/utils.py#L58)?

From [here](https://pytorch.org/docs/stable/notes/randomness.html#pytorch-random-number-generator), it shows 'You can use `torch.manual_seed()` to seed the RNG for all devices (both CPU and CUDA)'. Does it mean `torch.manual_seed()` is also for GPU?

However, from [here](https://pytorch.org/docs/stable/cuda.html#torch.cuda.manual_seed), it shows that `torch.cuda.manual_seed(seed)` and `torch.cuda.manual_seed_all(seed)` are needed to set seed for GPU. I feel a little confused now.

**Comment by haipinglu** [comment]
The best way to find out is to test the two versions to see which one is (more) reproducible. 


The mmcv version does seem to be recent and from a top group so maybe that's good practice (at least, no harm). The current version follows the [official PyTorch guideline on reproducibility](https://pytorch.org/docs/stable/notes/randomness.html#pytorch-random-number-generator).

This question may be best answered via [creating an issue at the PyTorch library](https://github.com/pytorch/pytorch/issues).
