### ISSUE TITLE
Unnecessary `kale.embed.video_cnn`

### ISSUE THREAD

**Issue by haipinglu** [pykale/pykale#34]
To me, `kale.embed.video_cnn` is not necessary just for two algorithms. This introduces unnecessary depth to the API. It will be needed only if `embed` becomes too big in future. Change it to something like `video_i3d` or `video_res3d` will be more compact and convenient to use.

**Comment by XianyuanLiu** [comment]
Got it and I have updated it in #35. Is it okay now? Many thanks!
