### ISSUE TITLE
[Bug]got error while running tutorial

### ISSUE THREAD

**Issue by zj71** [pykale/pykale#368]
# 🐛 Bug

<-- got error while running tutorial  -->

## To reproduce

1. run the tutorial.ipynb

** Stack trace/error message **
```
ERROR: Package 'pykale' requires a different Python: 3.10.11 not in '<3.10,>=3.7'
/content/pykale/examples/digits_dann
```

## Additional context
should update pykale current code or downgrade by using code 

#install python 3.9
!sudo apt-get update -y
!sudo apt-get install python3.8
!sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1
!sudo update-alternatives --config python3
!apt-get install python3-pip
!python -m pip install --upgrade pip --user

then it will install successfully,
from config import get_cfg_defaults
but still get error: 
```
ModuleNotFoundError: No module named 'yacs' 
```

**Comment by haipinglu** [comment]
@XianyuanLiu Indeed, colab also updated recently so we may need to speed up the migration to -py3.7 & +py3.10, unless you have ideas of other quick fixes. I tried that even after your PR merged today, our collab tutorial still cannot run https://colab.research.google.com/github/pykale/pykale/blob/main/examples/digits_dann/tutorial.ipynb

**Comment by XianyuanLiu** [comment]
Although `!sudo update-alternatives --config python3` changes the Python version in Colab, the implementation of the example code continues to use Python 3.10, causing this issue. After many tries, I have not successfully changed the Python version in the implementation. One possible solution is to create a virtual environment in Colab for version management, but the better solution is to upgrade our PyKale. It is undertaken in PR #370, which still has some bugs.
