### ISSUE TITLE
[Bug] Error raised by version mismatch between PyTorch and Lightning while running tutorial

### ISSUE THREAD

**Issue by xianyuanliu** [pykale/pykale#376]
# 🐛 Bug

PyKale sets PyTorch (>=1.11.0) and Lightning (>=1.3.0,<=1.6.5) in the [setup](https://github.com/pykale/pykale/blob/main/setup.py).
Therefore, in the [digits_dann tutorial](https://colab.research.google.com/github/pykale/pykale/blob/main/examples/digits_dann/tutorial.ipynb), PyKale installs PyTorch 2.0.0 (the latest) and Lightning 1.6.5. However, these two are not compatible, causing Misconfiguration Exception.

## To reproduce
Run [digits_dann tutorial](https://colab.research.google.com/github/pykale/pykale/blob/main/examples/digits_dann/tutorial.ipynb) and `%time trainer.fit(model)` returns the error.

** Stack trace/error message **
```
MisconfigurationException: The provided lr scheduler `LambdaLR` doesn't follow PyTorch's LRScheduler API. You should override the `LightningModule.lr_scheduler_step` hook with your own logic if you are using a custom LR scheduler.
```

## Expected Behaviour
No errors.

## Environment
Default tutorial environments, including
pytorch-lightning-1.6.5
torch-2.0.0+cu118
torchvision-0.15.1+cu118

## Additional context
Two solutions:
1. Fix the PyTorch version <=1.13.1. Simplest but temporal.
2. Update Lightning to 2.x. (may raise issues as discussed in #367)

**Comment by haipinglu** [comment]
@XianyuanLiu Temporal fix will lead to future problems still so we may consider updating to Lightning 2.0+, released in March 2023. This might need some substantial efforts that you may help take a look first (e.g. have you tried Lightning 2.0+?) and then we can discuss tomorrow.

@Mdnaimulislam Update the 3.7 in docs etc in PyKale as a separate PR.

**Comment by XianyuanLiu** [comment]
Sure, let's talk about it tomorrow. Shall we first do the temporal fix to make the tutorial work? 

I created BaseNNTrainer using Lightning 2.0.1. I am currently updating the codes related to the digit-dann tutorial. If we decide to upgrade tomorrow, I suggest first upgrading the setup and digit-dann tutorial to investigate the potential issues. Then, we update other examples in individual PRs.
