### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ZelinW** [pykale/pykale#38]
# 🐛 Bug

TypeError: summary() got an unexpected keyword argument 'depth'

## To reproduce

In pykale.examples.cifar_cnntransformer.main.py: model_stats = summary(net, (3, 32, 32), depth=10). When the parameter 'depth' exits, the code will return the error above.  When deleting it, the program runs normally.

```python
model_stats = summary(net, (3, 32, 32), depth=10)
```

** Stack trace/error message **
```
TypeError: summary() got an unexpected keyword argument 'depth'
```

## Environment

[pip3] numpy==1.19.0
[pip3] pytorch-lightning==1.1.3
[pip3] torch==1.7.1
[pip3] torchsummary==1.5
[pip3] torchvision==0.4.1
[conda] blas                      1.0    
[conda] cudatoolkit               11.0.221       
[conda] mkl                       2020.2       
[conda] mkl-service               2.3.0         
[conda] mkl_fft                   1.2.0        
[conda] mkl_random                1.1.1   
[conda] numpy                     1.19.2        
[conda] numpy-base                1.19.2      
[conda] numpydoc                  1.1.0     
[conda] pytorch                   1.7.0  
[conda] torchvision               0.8.1

Process finished with exit code 0

**Comment by RaivoKoot** [comment]
Hi, Great report! This is my fault for not documenting it correctly. 

There are two pip libraries that are almost the same, called torchsummary. One of them allows the `depth` parameter, one of them does not.
The following is the more popular one that does not use the depth parameters` https://pypi.org/project/torchsummary/`. (you probably have this one installed)  
  
This one, `https://pypi.org/project/torch-summary/`, is the less known one but allows you to use a `depth` parameters that controls how much detail is displayed when printing out an overview of the model architecture.

# Fix
You can either just remove the `depth` parameter from the function call, or remove the torchsummary library from your pip libraries and install the torch-summary library instead.

**Comment by RaivoKoot** [comment]
I have removed that parameter from that code line, because otherwise other people will run into the same issue.
