### ISSUE TITLE
[Bug] add library "tqdm" to install dependencies

### ISSUE THREAD

**Issue by RaivoKoot** [pykale/pykale#39]
Haiping,
Could you please add the pip library `tqdm` to the install dependencies. 

This will prevent an issue when people try to run the video loader example. Unfortunately, when `tqdm` is not installed and one attempts to use it, it does not give a clear error such as `tqdm is not installed`. Instead, it gives a cryptic error message that does not make it clear what the problem is.

**Comment by haipinglu** [comment]
Which min-version shall we specify? 

It is currently specified in `extras_require` of `setup.py` without a version specified but not in `requirements.txt` yet. We need to discuss what will be the `install_requires` and `extras_require`, maybe in the next PyKale meeting and with the help of Bob and/or other RSE colleagues.

This issue belongs to the dependencies card.

**Comment by RaivoKoot** [comment]
The minimum version should be `4.1.0`. 
Yes, we can talk about this in the next meeting.

**Comment by RaivoKoot** [comment]
I can't find a label called "dependencies". Can you explain that?

**Comment by haipinglu** [comment]
Sorry for not being clear enough earlier. What I wanted to say was that "dependencies" is the second item on our checkbox in the project board. I have created a card for it https://github.com/pykale/pykale/projects/9#card-52913368. 

I am not sure whether we want to create an additional label for it so I just put the two cards one on the top of the other. I only created one additional label for refactor in addition to the default labels provided by GitHub (10 in total). Even if we want to create a label, we may consider more broader term such as "setup" to cover a broad range of (potential) issues.

We may discuss the fineness of issue labels in the next/following meetings. I've just created another card https://github.com/pykale/pykale/projects/9#card-52936416

I think you can add `tqdm` to requirements.txt first. `setup.py` needs more considerations that may need RSE consultation.

**Comment by RaivoKoot** [comment]
Thanks for the explanation. Sounds good. Will discuss next time.

**Comment by haipinglu** [comment]
Added via commit https://github.com/pykale/pykale/commit/046e2c25f5571b91b0e7281f0826ca55bd841d17
