### ISSUE TITLE
[Refactor] Considering the incorporation of the OneHotEncoder from scikit-learn into PyKale

### ISSUE THREAD

**Issue by SinaTabakhi** [pykale/pykale#393]
When [PR #361](https://github.com/pykale/pykale/pull/361) is merged into PyKale, the `ToOneHotEncoding` class in [tabular_transform.py](https://github.com/pykale/pykale/pull/361/files#diff-2f32f0e45a0f6eb7fd8fc63cef5fbe2bd545a3fd25ce0518691c89e88eee12ae) module may need to be refactored, taking inspiration from its implementation in scikit-learn:
https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html#sklearn-preprocessing-onehotencoder

Consolidating the usage of OneHotEncoder in other PyKale modules is necessary.

**Comment by haipinglu** [comment]
@SinaTabakhi It will be better to capture this in (the same or new) discussions.
