### ISSUE TITLE
[Refactor] Merge modules `losses`, `distance`, and `metrics` to one

### ISSUE THREAD

**Issue by wenruifan** [pykale/pykale#402]
# Merge modules `losses`, `distance`, and `metrics` to one.
## Modules to be merged
- kale.utils.distance
- kale.predict.losses
- kale.evaluate.metrics
## Impact on code structure
The functions in these modules performed similarly, like calculating loss, accuracy, etc. It could be confusing when people try to use them or contribute to the library.
The import parts in some files may be changed.

**Comment by xianyuanliu** [comment]
Discussion #399 from @SinaTabakhi mentioned the same issue, which is helpful and constructive. We need to close #399 as well, once this issue is resolved.
