### ISSUE TITLE
[Refactor] Let one config file contain all hyperparameters.

### ISSUE THREAD

**Issue by wenruifan** [pykale/pykale#411]
In common projects, the config.yaml file will contain all adjustable hyperparameters for users to customize. However, in our Pykale, it contains just a small part.

For the very beginners who just want to let the demos work on their own data, it is fine and easy. But for those who request higher level of customization, they gave to figure out how yacs works, how the values in yaml file overwrite those in config.py at first. Then, compare carefully which hyperparameters can be changed in yaml and which have to be modified in config.py. It leads to great inconvenience.

Therefore, I suggest we put all hyperparameters in one file. Therefore, for beginners, it is not hard to find where to change the root path to their data. And for other higher level user, it is easy to configure the models and training/testing process according to their own situation.

This file can be either a config.py or a config.yaml. I personally prefer yaml because there can be several configurations defined under one unified standard, which is given in config.py.

All in all, config.py is to define what hyperparameters are required in the projects and config.yaml gives the values of these hyperparameters.

## Modules that will be modified
All demos with config.yaml.
## Impact on code structure
Add parameters in config.yaml.
## Impact on speed
No or very minos.
## Will this be a breaking change?
No

**Comment by xianyuanliu** [comment]
Thanks for bringing this to our attention. May I know your opinion? @shuo-zhou

**Comment by xianyuanliu** [comment]
Resolved. For simplicity, we will keep only the essential hyperparameters in the demo YAML file. In the future, if needed, we'll provide a separate YAML file containing the complete hyperparameters for users who need them.
