### ISSUE TITLE
[Refactor] GitHub actions caching 

### ISSUE THREAD

**Issue by wang-hlin** [pykale/pykale#419]
Datasets are downloaded every time a test runs, this step is unnecessary and takes long time (>20 mins) to process. The aim is to remove all data download code from `test` folder and cache the data, so data can be called from cache each time running the test.

**Comment by xianyuanliu** [comment]
We have divided the test data downloading process from the test cases and are now moving on to the next stage: implementing caching and restoration of the downloads.
