### ISSUE TITLE
[Bug] Installation on Mac

### ISSUE THREAD

**Issue by liudaotan** [pykale/pykale#78]
# 🐛 Bug

## To reproduce

1. pip install pykale[extras]
2. pip install .[extras] 
3. pip install -e .[dev]

** Stack trace/error message **
```
zsh: no matches found: .[extras]
zsh: no matches found: pykale[extras]
zsh: no matches found: .[dev]
```

## Environment
active environment : base
    active env location : /opt/anaconda3
            shell level : 2
       user config file : /Users/liudaotan/.condarc
 populated config files : /Users/liudaotan/.condarc
          conda version : 4.9.2
    conda-build version : 3.20.5
         python version : 3.8.5.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/anaconda3/pkgs
                          /Users/liudaotan/.conda/pkgs
       envs directories : /opt/anaconda3/envs
                          /Users/liudaotan/.conda/envs
               platform : osx-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Darwin/20.3.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.7
 - OS (e.g., Linux): Mac (M1)
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): 
 - Python version: 3.8
 - CUDA/cuDNN version: null
 - GPU models and configuration: 
 - Any other relevant information:

## Additional context
When I change the code as following , every thing goes well.
1. pip install 'pykale[extras]'
2. pip install '.[extras]' 
3. pip install '-e .[dev]'

**Comment by haipinglu** [comment]
You only need to choose _one of the `pip install` options_ from the installation instruction to install. Not sure why you are doing three of them in sequence here, i.e. you are installing the stable and then using installing from source. 

Do you have the same problem if you just do one `pip install` (e.g. `pip install pykale`)?

**Comment by liudaotan** [comment]
I wasn't sure which one I should install, so my team member and I did them in sequence . `pip install pykale` was fine. The problem I'm reporting only occurs when using [], such as `pip install 'pykale[extras]'`. Fortunately though, this doesn't affect running `pytest`. Thank you.

**Comment by haipinglu** [comment]
Options are explained in the comments.
If you are not sure, pick the simplest option `pip install pykale` can do. You could install other packages later when needed.
You can show me live in our next meeting.

@pz-white Do you have a mac to test whether `pip install pykale[extras]` works (e.g. via a conda environment)? I do not have one.

**Comment by liudaotan** [comment]
Thanks a lot.

**Comment by bobturneruk** [comment]
@haipinglu we should consider extending our test matrix to cover MacOS and Windows 10. If we're targeting conda environments, we could do our testing in a conda environment on each OS. Maybe consider raising an issue?

ref: https://github.com/pykale/pykale/blob/master/.github/workflows/test.yml

**Comment by haipinglu** [comment]
> @haipinglu we should consider extending our test matrix to cover MacOS and Windows 10. If we're targeting conda environments, we could do our testing in a conda environment on each OS. Maybe consider raising an issue?
> 
> ref: https://github.com/pykale/pykale/blob/master/.github/workflows/test.yml

@bobturneruk Agree, e.g. most of our students are MacOS or Windows users. Could you make this change? Such as a PR so that we could discuss any issue and merge tomorrow if feasible. Many thanks.

**Comment by bobturneruk** [comment]
Hi @haipinglu - might not get it done by tomorrow, but I will look at this.
